server:
  port: 8080
  servlet:
    context-path: /game-price-tg-bot-api
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: GamePriceTelegramBot
  main:
    banner-mode: off

cheap-shark:
  url: https://www.cheapshark.com/api/1.0/
